### ISSUE TITLE
Cover templates for @wordpress/create-block and how to create multiple blocks

### ISSUE THREAD

**Issue by dgwyer** [ryanwelcher/twitch#1]
Hi Ryan, thanks for the great content so far!

So, I think in the first Twitch video you mentioned you might cover how to use templates for `@wordpress/create-block`. This would be great but also covering the best way to create multiple blocks with `create-block` could be well worth exploring too.

Looking forward to the next video.

**Comment by ryanwelcher** [comment]
@dgwyer thanks for the suggestion! That's a great idea. I did _sort_ of cover it in the [first stream](https://www.twitch.tv/videos/1151309353) but mostly just discussed it. I think it definitely worth revisiting on its own!

P.S thanks for adding me to your resources list :)
