### ISSUE TITLE
Creating a custom block that outputs a shortcode on the front end.

### ISSUE THREAD

**Issue by ryanwelcher** [ryanwelcher/twitch#2]
This was suggested by @paaljoachiml in [WordPress core slack](https://wordpress.slack.com/archives/C02QB2JS7/p1632926072434900?thread_ts=1632925982.432700&cid=C02QB2JS7) in reference to [this ticket](https://github.com/WordPress/gutenberg/issues/34939).

**Comment by paaljoachim** [comment]
Hey Ryan

There are a lot of current plugins that add a shortcode to show something on the frontend. Moving from Shortcode to a block would be very beneficial for a lot of people.

Users would be able to interact with the block on the backend, and perhaps have access to sidebar settings and a toolbar to add additional modifications in the backend which will also be seen on the frontend.

**Comment by ryanwelcher** [comment]
@paaljoachim thanks for adding those details!

**Comment by ryanwelcher** [comment]
This topic was streamed and can be [seen here](https://www.youtube.com/watch?v=mVuGLI9kbcc)

**Comment by paaljoachim** [comment]
It would be helpful to add written summary of each stream.
1- The goal.
2- Difficulties along the way.
3- Conclusion with code example.

Thanks!

**Comment by ryanwelcher** [comment]
@paaljoachim I add a summary to the main readme file in the root of this repo after every stream.

**Comment by paaljoachim** [comment]
What about adding a gist after each stream showing the final result of the code?
As one could get a description and the code to test out.

**Comment by ryanwelcher** [comment]
The final code for each stream is included in this repo both in `trunk` and as its own branch. See the[ README](https://github.com/ryanwelcher/twitch/blob/trunk/README.md) file for the branch name. I'd prefer to keep this repo as the primary location for all of the code generated during a stream rather.
